name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Cocoapods
      uses: maxim-lobanov/setup-cocoapods@v1
      with: 
        podfile-path: Example/Podfile.lock
    
    - name: Xcode Build
      uses: devbotsxyz/xcode-build@v1.0.0
      with:
        workspace: Example/UICodeKit.xcworkspace
        scheme: UICodeKit-Example
